[versions]
kotlin = "2.3.0"
thrift = "0.22.0"
httpclient = "4.5.14"
slf4j = "2.0.16"
javax-annotation = "1.3.2"

[libraries]
apache-thrift = { group = "org.apache.thrift", name = "libthrift", version.ref = "thrift" }

javax-annotationApi = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "javax-annotation" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
apache-httpClient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclient" }

[plugins]
kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}

[bundles]
